development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: timetracker_development
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
staging:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: timetracker_development
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: blinq_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING